linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gosec
    - bodyclose
    - errname
    - errorlint

linters-settings:
  staticcheck:
    checks:
      - all

  errcheck:
    check-type-assertions: true

  gosec:
    excludes:
      - G107 # allow non-constant URLs (needed for version check)
